import type { Metadata } from "next";
import { Inter } from "next/font/google";
import PrelineScript from "@/app/components/PrelineScript";
import LeftSidebar from "./components/Navbar"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <LeftSidebar />
          <div className="h-[calc(100vh-70px)] bg-zinc-900">
            {children}
          </div>
      </body>
          <PrelineScript />
    </html>
  );
}
